# Generated by Django 2.2 on 2020-01-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThankYou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('reason_for_entering', models.TextField()),
                ('in_time', models.DateField(auto_now_add=True)),
                ('out_time', models.DateField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='')),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
