# Generated by Django 2.2 on 2020-01-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0002_auto_20200130_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='in_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
